packetbeat.inputs:
  - type: pcap
    path: "/pcap/4SICS-GeekLounge-151022.pcap"
    snaplen: 65535
    buffer_size_mb: 100
    # ignore_older: 0
    read_from_head: true

packetbeat.protocols:
  - type: http
    ports: [80, 8080, 8000, 5000, 8002]
  - type: dns
    ports: [53]
  - type: tls
    ports: [443, 8443]
  - type: sip
    ports: [5060, 5061]
  - type: mysql
    ports: [3306]
  - type: redis
    ports: [6379]

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"
